"""Doctor conversation model for storing doctor-patient AI discussions."""

import json
import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import relationship

from app.database import Base


class DoctorConversation(Base):
    """
    Model for storing doctor's AI conversations about specific patients.

    These are conversations where a doctor discusses a patient's case
    with the AI assistant to get clinical insights and recommendations.
    """

    __tablename__ = "doctor_conversations"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    doctor_id = Column(
        String(36),
        ForeignKey("doctors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    patient_id = Column(
        String(36),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Conversation content stored as JSON
    messages_json = Column(Text, default="[]")

    # Summary of the conversation (generated by AI)
    summary = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    doctor = relationship("Doctor", backref="ai_conversations")
    patient = relationship("Patient", backref="doctor_ai_conversations")

    @property
    def messages(self):
        """Get messages as a list."""
        return json.loads(self.messages_json) if self.messages_json else []

    @messages.setter
    def messages(self, value):
        """Set messages from a list."""
        self.messages_json = json.dumps(value, ensure_ascii=False) if value else "[]"

    def add_message(self, role: str, content: str):
        """Add a message to the conversation."""
        messages = self.messages
        messages.append(
            {
                "role": role,
                "content": content,
                "timestamp": datetime.utcnow().isoformat(),
            }
        )
        self.messages = messages

    def __repr__(self):
        return f"<DoctorConversation doctor={self.doctor_id} patient={self.patient_id}>"
